# Generated by Django 4.2.7 on 2023-11-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=40)),
                ('subject', models.CharField(max_length=15)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='causers',
            options={'ordering': ('-id',)},
        ),
    ]
