# Generated by Django 4.2.7 on 2023-12-18 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_donation_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='number',
            old_name='number',
            new_name='amount',
        ),
    ]
